services:
  - docker
  - mysql

language: go

go:
  - "1.9"

before_install:
  - mysql -e 'CREATE DATABASE koj_test CHARACTER SET utf8mb4;'

install:
  - ./setup.sh

jobs:
  include:
    - stage: test
      script:
      - go test ./server/...
      - go test ./nekonote/...
    - stage: deploy docker image
      if: branch = master
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t gedorinku/koneko-online-judge ./server
      - docker push gedorinku/koneko-online-judge

notifications:
  email:
    on_success: never
    on_failure: always
