services:
  - docker
language: go
go:
  - "1.9"
install:
  - ./setup.sh
script:
  - go test ./server/...
  - go test ./nekonote/...

notifications:
  email:
    on_success: never
    on_failure: always
