services:
  - docker
  - mysql

language: go

go:
  - "1.12.6"

jobs:
  include:
    - stage: test
      install: skip
      script:
      - mysql -e 'CREATE DATABASE koj_test CHARACTER SET utf8mb4;'
      - ./setup.sh
      - go test ./server/...
      - go test ./runner/...
      - go test ./nekonote/...
    - stage: deploy docker image
      if: branch = master AND type != pull_request
      install: skip
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t programminglab/koneko-online-judge .
      - docker push programminglab/koneko-online-judge

notifications:
  email:
    on_success: never
    on_failure: always
