version: "3"

services:
  koneko:
    build: ./server
    command: ["./wait-for-it.sh", "mysql:3306", "--", "./run.sh"]
    environment:
      KOJ_DB_DRIVER: "mysql"
      KOJ_DB_SPEC: "root:${KOJ_DB_PASSWORD}@tcp(mysql:3306)/koj?charset=utf8&parseTime=True&loc=Local"
    depends_on:
      - mysql
    ports:
      - "2323:2323"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: 5m
        max-file: "10"

  mysql:
    image: mysql:5.7
    hostname: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "${KOJ_DB_PASSWORD}"
      MYSQL_DATABASE: "koj"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    logging:
      options:
        max-size: 5m
        max-file: "10"
    ports:
      - "33060:3306"

volumes:
  db-data:
    driver: local