FROM gcc:7.2.0
MAINTAINER gedorinku <gedorinku@yahoo.co.jp>

RUN apt-get update && apt-get install time

RUN apt-get update && apt-get install sudo

RUN mkdir /tmp/koj-workspace && chmod 777 /tmp/koj-workspace
