[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.8"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.8"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/go-mail/mail"
  version = "2.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/gocraft/work"
