[Koneko]
dbHost = "mysql:3306"
dbName = "koj"
dbUser = "root"
dbPassword = "password"
redisHost = "redis:6379"
debug = true

[SMTP]
host = "smtp"
port = 1025
noStartTLS = false
user = "user"
password = "password"
from = "hoge@example.com"

[Judgement]
# 同時に実行されるジャッジジョブの数
concurrently = 1

[Client]
basePath = "https://example.com"
# パスワードリセットページのパス
passwordResetPath = "/password_reset"
# ユーザー登録ページのパス
registrationPath = "/register"
