ignored = [
  "github.com/user/project/pkgX",
  "bitbucket.org/user/project/pkgA/pkgY",
  "github.com/ProgrammingLab/koneko-online-judge/server*"
]

[prune]
  go-tests = true
  unused-packages = true
